BEGIN
INSERT INTO TEACHERS (T_ID, T_NAME, T_TITLE)
VALUES (SEQ_TEA.NEXTVAL, 'Lavendelis',	'Researcher');
INSERT INTO TEACHERS (T_ID, T_NAME, T_TITLE)
VALUES (SEQ_TEA.NEXTVAL, 'Grundspenkis',	'Professor');
INSERT INTO TEACHERS (T_ID, T_NAME, T_TITLE)
VALUES (SEQ_TEA.NEXTVAL, 'Kirikova',	'Professor');
INSERT INTO TEACHERS (T_ID, T_NAME, T_TITLE)
VALUES (SEQ_TEA.NEXTVAL, 'Zagurskis',	'Professor');
INSERT INTO TEACHERS (T_ID, T_NAME, T_TITLE)
VALUES (SEQ_TEA.NEXTVAL, 'Grabis',	'Professor');
END;