
CREATE TABLE COURSES (
C_ID NUMBER PRIMARY KEY,
C_TITLE VARCHAR2(30),
C_TEACHER NUMBER,
C_C_POINTS NUMBER CHECK (C_C_POINTS > 0),
CONSTRAINT F_K_G_T FOREIGN KEY 
(C_TEACHER) REFERENCES TEACHERS(T_ID)
);